export const defaultDatosTabla = [
  [
    {value: '', readOnly: true},
    {value: 'Zona 1', readOnly: true},
    {value: 'Zona 2', readOnly: true},
    {value: 'Zona 3', readOnly: true},
    {value: 'Zona 4', readOnly: true},
    {value: 'Zona 5', readOnly: true},
    {value: 'Zona 6', readOnly: true},
    {value: 'Zona 7', readOnly: true},
    {value: 'Zona 8', readOnly: true},
    {value: '', readOnly: true},
  ],
  [
    {value: '1', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '2', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '3', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '4', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '5', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '6', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '7', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '8', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '9', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '10', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '11', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '12', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '13', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '14', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '15', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '16', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '17', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '18', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '19', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '20', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '21', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '22', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '23', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '24', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '25', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '26', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '27', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '28', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '29', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: '30', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
  [
    {value: 'KGadicional', readOnly: true},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
    {value: ''},
  ],
];

export const optionsServicesEstafeta = [
  {label: 'Dia Sig. (Aereo)', id: 'Dia Sig.', value: 'Dia Sig.'},
  {label: 'Terrestre', id: 'Terrestre', value: 'Terrestre'},
];

export const optionsServicesDHL = [
  {label: 'N (Aereo)', id: 'N', value: 'N'},
  {label: 'G (Terrestre)', id: 'G', value: 'G'},
];

export const copys = {
  basic_info_form_title: 'Formulario de informacion basica',
  username_input_label: 'Nombre de usuario',
  username_input_caption: 'Nombre con el que se identifica al usuario',
  reference_input_label: 'Referencia',
  reference_input_caption: 'Identificador en generacion de guias',
  data_sheet: 'Matriz de datos',
  currier_Est: 'Estafeta',
  currier_DHL: 'DHL',
  services_select_placeholder:
    'Selecciona el servicio al que cambiar la matriz',
};
